// Mocks generated by Mockito 5.4.6 from annotations
// in cherry_mvp/test/auth_ui_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cherry_mvp/core/models/model.dart' as _i6;
import 'package:cherry_mvp/core/router/nav_provider.dart' as _i8;
import 'package:cherry_mvp/core/utils/utils.dart' as _i2;
import 'package:cherry_mvp/features/login/login_model.dart' as _i7;
import 'package:cherry_mvp/features/login/login_repository.dart' as _i4;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlobalKey_1<T extends _i3.State<_i3.StatefulWidget>>
    extends _i1.SmartFake
    implements _i3.GlobalKey<T> {
  _FakeGlobalKey_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepository extends _i1.Mock implements _i4.LoginRepository {
  @override
  _i5.Future<_i2.Result<_i6.UserCredentials?>> login(
    _i7.LoginRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
              _FakeResult_0<_i6.UserCredentials?>(
                this,
                Invocation.method(#login, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
                  _FakeResult_0<_i6.UserCredentials?>(
                    this,
                    Invocation.method(#login, [request]),
                  ),
                ),
          )
          as _i5.Future<_i2.Result<_i6.UserCredentials?>>);

  @override
  _i5.Future<_i2.Result<_i6.UserCredentials?>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
              _FakeResult_0<_i6.UserCredentials?>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
                  _FakeResult_0<_i6.UserCredentials?>(
                    this,
                    Invocation.method(#signInWithGoogle, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Result<_i6.UserCredentials?>>);

  @override
  _i5.Future<_i2.Result<_i6.UserCredentials?>> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
              _FakeResult_0<_i6.UserCredentials?>(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i2.Result<_i6.UserCredentials?>>.value(
                  _FakeResult_0<_i6.UserCredentials?>(
                    this,
                    Invocation.method(#signInWithApple, []),
                  ),
                ),
          )
          as _i5.Future<_i2.Result<_i6.UserCredentials?>>);

  @override
  _i5.Future<_i2.Result<void>> fetchUserFromFirestore(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserFromFirestore, [uid]),
            returnValue: _i5.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#fetchUserFromFirestore, [uid]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(
                this,
                Invocation.method(#fetchUserFromFirestore, [uid]),
              ),
            ),
          )
          as _i5.Future<_i2.Result<void>>);

  @override
  _i5.Future<_i2.Result<void>> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#logout, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.Result<void>>.value(
              _FakeResult_0<void>(this, Invocation.method(#logout, [])),
            ),
          )
          as _i5.Future<_i2.Result<void>>);
}

/// A class which mocks [NavigationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationProvider extends _i1.Mock
    implements _i8.NavigationProvider {
  @override
  _i3.GlobalKey<_i3.NavigatorState> get navigatorKey =>
      (super.noSuchMethod(
            Invocation.getter(#navigatorKey),
            returnValue: _FakeGlobalKey_1<_i3.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
            returnValueForMissingStub: _FakeGlobalKey_1<_i3.NavigatorState>(
              this,
              Invocation.getter(#navigatorKey),
            ),
          )
          as _i3.GlobalKey<_i3.NavigatorState>);

  @override
  _i5.Future<dynamic> navigateTo(String? routeName, {Object? arguments}) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateTo,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> replaceWith(String? routeName, {Object? arguments}) =>
      (super.noSuchMethod(
            Invocation.method(
              #replaceWith,
              [routeName],
              {#arguments: arguments},
            ),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  _i5.Future<dynamic> navigateToAndRemoveUntil(
    String? routeName,
    _i3.RoutePredicate? predicate, {
    Object? arguments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #navigateToAndRemoveUntil,
              [routeName, predicate],
              {#arguments: arguments},
            ),
            returnValue: _i5.Future<dynamic>.value(),
            returnValueForMissingStub: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);

  @override
  void goBack([Object? arguments]) => super.noSuchMethod(
    Invocation.method(#goBack, [arguments]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> showPurchaseSecurity() =>
      (super.noSuchMethod(
            Invocation.method(#showPurchaseSecurity, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
