// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcXyGAO1lbA_QvN8MCRr1ywX5DrnAONio',
    appId: '1:693484617842:web:aa0c0048c117fa9d5042eb',
    messagingSenderId: '693484617842',
    projectId: 'cherrymvpnew', 
    authDomain: 'cherrymvpnew.firebaseapp.com',
    storageBucket: 'cherrymvpnew.firebasestorage.app',
    measurementId: 'G-63NEFVJ8WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNAaX0VXTOIUB4KpNHCVXsYFfaTJKF7g',
    appId: '1:693484617842:android:ee46d28d3a896c095042eb',
    messagingSenderId: '693484617842',
    projectId: 'cherrymvpnew',
    storageBucket: 'cherrymvpnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRY91zDkwHRMLEj8PZiY0XaK_xrTGwPno',
    appId: '1:693484617842:ios:194b4093594a81515042eb',
    messagingSenderId: '693484617842',
    projectId: 'cherrymvpnew',
    storageBucket: 'cherrymvpnew.firebasestorage.app',
    iosBundleId: 'com.cherry.cherrymvp',
  );
}
